name: Java

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        run: gradle build

      - name: Test
        run: gradle check

      - name: Test report
        uses: phoenix-actions/test-reporting@v8
        id: test-report                     # Set ID reference for step
        with:
          artifact: test-results            # artifact name
          name: Junit Tests                  # Name of the check run which will be created
          path: '*.xml'                     # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results